# Generated by Django 5.2 on 2026-02-16 05:44

import tane_web.id_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.CharField(default=tane_web.id_utils.generate_hashed_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
