# Generated by Django 5.2.11 on 2026-02-19 02:46

import tane_web.id_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_program_id_alter_siteprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStakeholder',
            fields=[
                ('id', models.CharField(default=tane_web.id_utils.generate_hashed_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Key Stakeholder',
                'verbose_name_plural': 'Key Stakeholders',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.CharField(default=tane_web.id_utils.generate_hashed_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('strategic_objective', models.CharField(max_length=255, verbose_name='Objetivu Estratejiku')),
                ('strategic_activity', models.TextField(verbose_name='Atividade Estratejiku')),
                ('success_measure', models.TextField(verbose_name='Sasukat Susesu nian')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Strategic Objective (Estratejia)',
                'verbose_name_plural': 'Strategic Objectives (Estratejia Sira)',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='StrategicValue',
            fields=[
                ('id', models.CharField(default=tane_web.id_utils.generate_hashed_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Strategic Value (Valor)',
                'verbose_name_plural': 'Strategic Values (Valores)',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
