# Generated by Django 5.2.11 on 2026-02-19 05:49

import tane_web.id_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_keystakeholder_strategicobjective_strategicvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.CharField(default=tane_web.id_utils.generate_hashed_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News item',
                'verbose_name_plural': 'News items',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='program',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='SuccessStory',
        ),
    ]
