# Generated by Django 5.2.11 on 2026-02-19 06:20

import django.db.models.deletion
import tane_web.id_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_newsitem_remove_successstory_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.CharField(default=tane_web.id_utils.generate_hashed_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'News tag',
                'verbose_name_plural': 'News tags',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='contact_phone',
        ),
        migrations.CreateModel(
            name='NewsGalleryImage',
            fields=[
                ('id', models.CharField(default=tane_web.id_utils.generate_hashed_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.newsitem')),
            ],
            options={
                'verbose_name': 'News gallery image',
                'verbose_name_plural': 'News gallery images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='content.newstag'),
        ),
    ]
