# Generated by Django 5.2.11 on 2026-02-19 06:52

import tane_web.id_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_newstag_remove_siteprofile_contact_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstrategiaItem',
            fields=[
                ('id', models.CharField(default=tane_web.id_utils.generate_hashed_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('objetivu_estratejiku', models.CharField(max_length=255, verbose_name='Objetivu Estratejiku')),
                ('atividade_estratejiku', models.TextField(verbose_name='Atividade Estratejiku')),
                ('sasukat_susesu_nian', models.TextField(verbose_name='Sasukat Susesu nian')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estratejia item',
                'verbose_name_plural': 'Estratejia sira',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationHistory',
            fields=[
                ('id', models.CharField(default=tane_web.id_utils.generate_hashed_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Organization history',
                'verbose_name_plural': 'Organization histories',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='StrategicObjective',
        ),
        migrations.DeleteModel(
            name='StrategicValue',
        ),
        migrations.RenameField(
            model_name='siteprofile',
            old_name='mission_statement',
            new_name='mision',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='hero_image_url',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='history',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='valor',
            field=models.TextField(blank=True),
        ),
    ]
