# Generated by Django 5.2.11 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_estrategiaitem_organizationhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='about_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='about_intro',
            field=models.TextField(blank=True),
        ),
    ]
