# Generated by Django 5.2.11 on 2026-02-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_siteprofile_about_intro_and_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystakeholder',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Subtítulu / Deskrisaun'),
        ),
        migrations.AddField(
            model_name='keystakeholder',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Títulu / Kategória'),
        ),
    ]
