# Generated by Django 5.2.11 on 2026-02-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_stakeholder_title_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='map_embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='map_location_label',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
