# Generated by Django 5.2.11 on 2026-02-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_profile_social_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='map_embed_url',
            field=models.TextField(blank=True),
        ),
    ]
