# Generated by Django 5.2.11 on 2026-02-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_map_embed_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
