# Generated by Django 5.2.11 on 2026-03-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_profile_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='historia_hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='perfil_hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='planu_hero_image_url',
            field=models.URLField(blank=True),
        ),
    ]
