# Generated by Django 5.2.11 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_profile_hero_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="home_hero_image_url",
            field=models.URLField(blank=True),
        ),
    ]
